# Generated by Django 4.1.3 on 2025-11-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Create_at", models.DateTimeField(auto_now_add=True)),
                ("Update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Enrollment", models.CharField(max_length=10, unique=True)),
                ("Create_at", models.DateTimeField(auto_now_add=True)),
                ("Update_at", models.DateTimeField(auto_now=True)),
                (
                    "School",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.school"
                    ),
                ),
            ],
        ),
    ]
